// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxnmehhjivogtkaggkrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4bm1laGhqaXZvZ3RrYWdna3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMDQzNDYsImV4cCI6MjA1NTg4MDM0Nn0.3eEkKtF7uHvfKTIoI_qdi70zIlOA1MpZpFcQd9VT9W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);